### ISSUE TITLE
Not reading the POI information

### ISSUE THREAD

**Issue by jpvguerreiro** [hulop/NavCogIOSv3#10]
Hi.

I have tried both the master and update-view branches with the wow-hokoukukan server, and it is not reading the POIs that are in the server when the "user" is passing by their location. 
Do I need to do something in order for it to read them (some parameter in the settings?), or it should be working?

Thanks,
Joao

**Comment by dsato80** [comment]
Hi Joao

I have reorganized some types of POIs recently.
Please use the latest working branch `development`

[POI spec](https://github.com/hulop/NavCogIOSv3/wiki/POI-specs) can be found here
