### ISSUE TITLE
Model composing is a mess

### ISSUE THREAD

**Issue by dsato80** [hulop/NavCogIOSv3#17]
https://github.com/hulop/NavCogIOSv3/wiki/Process-of-making-fingerprint-model

Let's discuss what is the best scenario for composing model data with new members, what are issues with the current status and what we should make to solve the issues.

The following is the current steps (and my comment for the step

- setup Map server / finger print server (should be merged
  - add a floor plan on finger print server (required manual process
  - compose floormaps.json and images and import into map server (manual operation, it should be auto

- finger print with NavCogFingerPrint (required manual process

- compose 2d map data
  - export data  from finger print server
  - unify coordinates (convert, or one possible solution is to support lat/lng in blelocpp
  - post-process for data cleansing (merge nearby data into a point, remove outlier, ...
  - execute machine learning
  - prepare image for map matching (can be a white image at start

- import the 2d map data to map server
- edit server_config.json file and plist presets file so that NavCog can use the data, and import it to map server

**Comment by dsato80** [comment]
Goal

1. seup map server (including finger print manager)
2. add a floor plan (map server use it
3. finger print
4. plot beacons
5. generate model (lots of things are done at the backstage
6. NavCog can localize

hmm, (5) is including too much things to be done automatically...

- Finger print server 
  - sampling data is in JSON (because using couch db)
  - floor plan is anchored with a global point and rotation
  - sampling data is managed in local coordinates for each floor plan (this is good so that the map scale / rotation / position can be modified later)

- Tools
  - local / global coordinate converter for JSON sample data

- NavCog blelocpp (localize engine)
  - load data from 2dMapData format
  - assumes sampling data is in CSV (I forgot the reason, but might be file size)
  - engine has function to read sampling data in JSON
  - assumes sampling data in meter coordinate
  - currently not able to manage multiple map files (means multiple floor plan should be unified

---
next step

- implement sampling data exporter 
- make blelocpp can load csv/json sample data

1. setup map server (including finger print manager)
2. add a floor plan (map server use it
3. finger print
4. plot beacons
5. generate model (lots of things are done at the backstage
5-1. export data in json with coordinate conversion on server
5-2. compose data with json sample (manual
5-3. configure server (manual
6. NavCog can localize (need to load json sample data

**Comment by colegleason** [comment]
Hey, I have some opinions on this, as I'm interested in getting the model composition easy enough for non-experts to do it. To that end, I think it would be nice if we could support a single public map server with an easy way for anyone to make new maps (others can host private map servers for private data).

If someone wants to add NavCog to their building, they would:

1.  Create a new, empty map on the NavCog server.
2. Create new layers and upload floor plans. For each floor plan, align on map visually.
3. Draw walkable areas, such as nodes and edges (we should automate this).
4. (optional) Mark spots where beacons should be places (beacon slots).
5. Place beacons in area using app so they are auto-added to map.
6. (optional) Mark fingerprint locations to get good coverage.
7. Fingerprint using app and have these auto-added and uploaded.

**Comment by vantasay** [comment]
I like Cole's idea which would need a very nice UI however, I'm not sure how nice our current UI is :) sorry my bad, failed to follow the project. But I like the idea to make thing integrated, people can setup their on tech stack if they want. Most of people want to try things out in a dummy way. So I think it would make it more acceptable.

**Comment by colegleason** [comment]
Also, we were just discussing this in person, but we need to simplify beacon IDs. There should only be one id for each beacon (and possible a separate id for beacon location ids). Juggling beacon product ids, minor ids, UUIDs, major ids, and map ids is too much.

NavCog should set one UUID per map, and maybe major ids for different areas/floors in a map. Minor IDs per beacon, of course. Minor IDs should be unique per area/floor (major id), but otherwise I think it's ok to repeat them in a map.

**Comment by dsato80** [comment]
Thanks @colegleason and @vantasay for commenting on this topic.

As for the @colegleason 's comment
1. currently it is managed by creating a new server. require account control, multi tenancy
3. automation is interesting, it might be done with vision techs
5. planned feature 
7-8. this is complicated issue, if you want to evaluate accurately, you need to correct accurate samplings. If you correct samplings accurately, you may get accurate result. We need to "estimate" the accuracy based on other data.

> NavCog should set one UUID per map, and maybe major ids for different areas/floors in a map. Minor IDs per beacon, of course. Minor IDs should be unique per area/floor (major id), **but otherwise I think it's ok to repeat them in a map.**

"Major-Minor" pair should be unique but no other restriction.

**Comment by colegleason** [comment]
@dsato80 How reasonable would it be to move to global coordinates for everything?

**Comment by dsato80** [comment]
@colegleason good question! It is mostly because of localization.

- Pedestrian network is managed in global.
- Beacons / fingerprints are managed in local with an global anchor (on a floor plan).
- Current localization engine is able to handle only local coordinates

If you manage everything in global, you need to modify the engine or convert back into local.

Another reason is in measurement. It is relatively easy to determine the location in a building, but it is relatively hard to determine the location in global.

**Comment by dsato80** [comment]
The current model composing tool is working.
