### ISSUE TITLE
Start button is grayed out after selecting a destination

### ISSUE THREAD

**Issue by colegleason** [hulop/NavCogIOSv3#19]
I opened NavCog CMU map, pressed Search, pressed Select Destination, selected the Robotics lab, but the Start button was disabled. This is an intermittant issue, as restarting the app fixed it.

**Comment by dsato80** [comment]
The start button is disabled when your location is not available. There is a function to init localizer if the estimated location seems to be apart from actual location. Sometimes it is initialized with false positives. So even if you get location before selecting a destination the location can be lost. It highly depends on localizer data.
