### ISSUE TITLE
Navigation interface and Help page modifications for hotel demo

### ISSUE THREAD

**Issue by loopRW** [hulop/NavCogIOSv3#25]
The current help page is OK.  We need to put it as help when loading navcog. Should this be first time? should it be with a checkbox "Don't show next time?"

modifications to the interface:

- Change "search with dialog" to "voice search". Dialog in GUI is typically a yes/no popup window.
- Should we remove FROM area in "search"? in what case will a user use it at the moment?
- If we remove "FROM", we should change "TO" -> "Destination"
- Should recent routes be just recent destinations?
- Remove preview, we have the app for that.
- "Setting"->"Settings"
- since facility info is critical info in this case, should we put default on?
- "Ignore facility info" -> "Guidance instructions only"?
- we may need to go back if someone selects map or mode wrong

modifications to the help page:

How to use NavCog

[add] "Navcog is a navigation software, similar to GPS navigation used when driving by car. This page will explain how to use NavCog"

[include Mode as is]

[include Spoken dialog as is]

Visually impaired person mode:

[add]
"Hold the phone in your free hand. When navigating in this mode, you will first hear a high level description of the route: its destination and length, followed by the first instruction (e.g., go straight and turn left in 30ft). Before each instruction, the system will ask for your attention with a vibration and a short ping sound. While you are walking towards the next turning point the system will periodically tell you the distance to it and it will tell “approaching” when you are close to it. After that the phone will tell you to turn. A turn is in general about 90°, while a slight turn is smaller. The phone will play a sound and vibrate when you have turned enough, so be careful not to turn too little or too much. Afterwards, the system will give you the distance to the next turning point and it will hint what will the next turn be (e.g, turn left at the end of the corridor). While navigating the phone will also tell you information about the environment, for example when the floor changes from carpet to marble, and when you have features of interest (restrooms, water fountains, notable places) or obstacles near you while traversing the environment. Use that information for avoiding collisions and as a confirmation during navigation. The only possible command is a tap on the screen, which will say your current status in case you need confirmation on where you are (for instance, proceed 20 feet and turn right)."

Search:
- Search button in top right corner will take you to the destination search screen.
- Select a departure place in the "FROM" field on top of the screen. You can select "current location" to start from your current position, or select from a list of nearby locations.
[remove if we eliminate "FROM"]
- Select a destination in the "TO" field right underneath. It is possible to do a voice search, or select from a list of possible destinations.
[Change "search with dialog" to "voice search"]
[If we remove "FROM", we should change "TO" -> "Destination"]
- You can select one of your recent routes from the list in the middle of the screen.
[if recent destinations change "routes" -> "destinations"]
[Remove preview]
- Route options are on the bottom center of the screen
[Include the bullet points of route options]

Setting:
["Setting" -> "Settings"]
- Settings button is on top left of the interface.
[include speech speed bullet]
[Remove preview speed and preview with action]
- Ignore facility info: Provide only guidance instructions. Do not read facility information such as rooms, offices, restrooms...
[Change "Ignore facility info" -> "Guidance instructions only"?]
[Remove launch exercise]
[include distance unit bullet]
- Open help page: open this page.

**Comment by dsato80** [comment]
please modify help page here https://github.com/hulop/hulop.github.io

> - The current help page is OK.  We need to put it as help when loading navcog. Should this be first time? should it be with a checkbox "Don't show next time?"

It will not be on NavCog but on MapServer. It will be shown once.
I think it should be different from general help page. It should emphasize some tips to use NavCog.

> - Change "search with dialog" to "voice search". Dialog in GUI is typically a yes/no popup window.
> - Remove preview, we have the app for that.
> - "Setting"->"Settings"

agree

> - since facility info is critical info in this case, should we put default on?
> - "Ignore facility info" -> "Guidance instructions only"?

This is for your previous experiment. I will move it to developer menu.

> - Should we remove FROM area in "search"? in what case will a user use it at the moment?
> - If we remove "FROM", we should change "TO" -> "Destination"

not agree.
from is needed for demo/debug purpose.

> - Should recent routes be just recent destinations?

pending / rename to "history"

> - we may need to go back if someone selects map or mode wrong

It takes time to fix memory leak issue.
It is not easy to remove all instances when you go back to the initial page.

**Comment by jpvguerreiro** [comment]
Actually, for the comment below it is better to ignore this information. We have several rooms, so we don't want NavCog to read all the rooms. We can add _nav_info_ when we really want it to read something (e.g. restrooms, coffee shop).. but generally we do not want facility information to be read.

        since facility info is critical info in this case, should we put default on?
        "Ignore facility info" -> "Guidance instructions only"?

This is for your previous experiment. I will move it to developer menu.

**Comment by loopRW** [comment]
"recent" is better than "history"

as for "From", besides demo/debug purposes (which should then be administrator mode option), i don't see how a blind user would use it.

**Comment by dsato80** [comment]
@jpvguerreiro @loopRW 
As for facility info, it totally depends on the situation.
If there are shops, users may want to know. But if there are a lot of small classrooms, they don't.
Even if there are shops, if a user is familiar with the place he/she would not want to the information.
I think it is related to user's knowledge. 

I will remove from the normal menu. (default = read everything)
Move it to developer menu (we can control by server setting)
We need to think about the user can turn on/off the function or more flexible way.

as for "From", you are right but it affects a lot to existing demos.
I can try to hide "From" (current location) with an option (default off) and set the option on the server for the next demo.

**Comment by jpvguerreiro** [comment]
I agree it depends on the situation. In this situation, it is good to read some of the things that are on the first floor (for example, registration desk, restaurant, coffee shop).. but reading all the rooms on the other floors is overwhelming... there are rooms every 2 meters (on both sides).

Since we probably do not have time to customize that.. I would say that it would be better to disable reading it... and we would add additional _nav_info_ for the ones we want the system to read? Other option would be to use a flag on the minor_category?

Are there any other alternatives?
Let us know what you think.

**Comment by dsato80** [comment]
One idea is to automatically eliminate some repeating similar POIs. The point is how to define it.

**Comment by dsato80** [comment]
Close this topic and open a new issue.
