### ISSUE TITLE
labels overlap

### ISSUE THREAD

**Issue by loopRW** [hulop/NavCogIOSv3#26]
sometimes when going into settings, in top left corner "settings" label remains and overlaps with "back" label. when pressing it will just load another settings dialog and it is not possible to go back.
We will post a screenshot.

**Comment by jpvguerreiro** [comment]
Example below:

![img_0001](https://user-images.githubusercontent.com/1678994/31782755-f864b594-b4c9-11e7-8155-f9619719a872.PNG)

**Comment by dsato80** [comment]
It's just a navigation controller transition with storyboard segue. I have no idea for this bug. (iOS bug?)

**Comment by momomd** [comment]
I assume that this has to do with the layout.

If it is not set for horizontally centered, it might move to different
location depending on the screen size.

**Comment by dsato80** [comment]
I think no way to set layout on navigation bar.
