### ISSUE TITLE
Locations gets lost 

### ISSUE THREAD

**Issue by momomd** [hulop/NavCogIOSv3#32]
Location gets lost.
On GHC 8F: near offices #8816-8818, 8203 and 8100. 
On GHC 7F: near 7500A, 7700, 7403, 7707. 

Sometimes it localizes a user on 3F (near the cafe) when a user is near 7701 (the bridge)

**Comment by dsato80** [comment]
Hi @momomd, I understand the issues on your location.
But this issue is not directory related to the public repository, so let's discuss about this issue via email.
