### ISSUE TITLE
[v1.31.2] Server list configuration mechanism not working

### ISSUE THREAD

**Issue by falcon03** [hulop/NavCogIOSv3#37]
According to the Wiki

https://github.com/hulop/NavCogIOSv3/wiki/Configure-NavCog3

it should be possible to configure the server list by uploading the serverlist.txt or serverlist.json file to the app through iTunes file sharing. However the mechanism is not working for me: while I can see the app among the ones that support file sharing, the button to add a document to it is always dimmed. Dragging/dropping and copying/pasting the file does not work as well. I am using the Navcog app available via the iOS AppStore. I am running iTunes 12.7.5 under mac OS 10.13.5 and my iPhone is running iOS 11.4.

I double checked that the problem is not related to my configuration and in fact it looks like it is not: I can use iTunes file sharing as expected with other apps.

**Comment by dsato80** [comment]
Hi @falcon03,

My configuration does work. (iTunes 12.7.5.9, macOS 10.13.4, iOS 11.3.1)
Did you try to reinstall the app?
