### ISSUE TITLE
Compile Error - Redefinition of 'ACTION' in HLPSetting.h

### ISSUE THREAD

**Issue by donghyunyoo** [hulop/NavCogIOSv3#40]
I downloaded the source code and built.
I got errors "Redefinition of 'ACTION'" in line 41 of HLPSetting.h.
"ACTION" is defined in search.h like this.

typedef	enum {
	FIND, ENTER
} ACTION;

How can I fix it?

**Comment by dsato80** [comment]
I have pushed the latest change into the master branch. Could you please check it again?

**Comment by donghyunyoo** [comment]
Yes it works. 
Thanks
