### ISSUE TITLE
Developer menu can't be displayed

### ISSUE THREAD

**Issue by peifuji** [hulop/NavCogIOSv3#45]
I want to use developer menu.
・By using NavcogTool,I made dev.hashfile and dev.keyfile .
・Both dev.hashfile and dev.keyfile  were copied into Document directory of NavCog app via iTunes File sharing function.

But the setting did not change .  How can I switch modes ?

**Comment by daisukes** [comment]
You need to build your NavCog with your [dev.hashfile](https://github.com/hulop/NavCogIOSv3/blob/master/NavCog3/dev.hashfile) and copy only the dev.keyfile into the Document directory of NavCog via iTunes.

**Comment by peifuji** [comment]
Thank you.
I could use developer menu.
