### ISSUE TITLE
Some options cannot be changed

### ISSUE THREAD

**Issue by loopRW** [hulop/NavCogIOSv3#5]
Joao and I tried to install NavCog 3 and there are a few problems in setting the options:

1. changing guidance mode option in iphone settings (wheelchair/blind) does not have any effect on gui. it can be changed inside the app.
2. the default server cannot be deleted
3. a new server cannot be created

Also, is it possible for you to create and share with us another server instance that Joao can work on?

**Comment by dsato80** [comment]
I believe the setting bug was fixed.
Could you check the latest code.
I'm working on update-view branch.

@itohtaka will help you for the server
