### ISSUE TITLE
Wrong backword announce

### ISSUE THREAD

**Issue by daisukes** [hulop/NavCogIOSv3#50]
While walking on a long curved path towards a different floor, it gives wrong “going backward” announcements.

The path is almost a half-circle ramp from the 3rd floor to the 5th floor.

**Comment by daisukes** [comment]
@kentarou-fukuda 
Could you check the branch named bug-fix-50?

**Comment by kentarou-fukuda** [comment]
Thank you! We will try to check it.

**Comment by daisukes** [comment]
@kentarou-fukuda 
Have you tested this fix? If it works I will merge it to the master branch.

**Comment by kentarou-fukuda** [comment]
Excuse me, but we could not test it at that time, and used a workaround (divide the route into several links).
For the test purpose, is it possible to build NavCog test flight with this fix? If so, I will prepare test environment and ask our team member to test it.
