### ISSUE TITLE
pod installation issue

### ISSUE THREAD

**Issue by karthickkck315** [hulop/NavCogIOSv3#51]
While am install pod 'openCv Dynamic' getting below issue. Please suggest me any solution.

<img width="569" alt="Screenshot 2021-07-27 at 9 09 59 AM" src="https://user-images.githubusercontent.com/4092436/127091626-91b6fdc3-a021-4ce1-ae72-8e330498d233.png">

**Comment by daisukes** [comment]
Hi @karthickkck315 

I tried `a25a8583@master` and had no issue with pod install.
Could you let us know which `commit-hash@branch` you tried to build?
Information about your environment may help too.


```
% pod install
Analyzing dependencies
Fetching podspec for `OpenCV-Dynamic` from `https://raw.githubusercontent.com/hulop/blelocpp/v1.3.6/platform/ios/podspecs/OpenCV-Dynamic.podspec`
Downloading dependencies
Installing FormatterKit (1.9.0)
Installing OpenCV-Dynamic (4.1.2)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `NavCog3.xcworkspace` for this project from now on.
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.

--------
% pod --version
1.10.1
% xcodebuild -version
Xcode 12.5
Build version 12E262
% sysctl -n machdep.cpu.brand_string

Apple M1

```

**Comment by karthickkck315** [comment]
I tried master branch only please find the screen shot here.

<img width="962" alt="Screenshot 2021-07-28 at 7 42 00 AM" src="https://user-images.githubusercontent.com/4092436/127252542-51457ec3-8b86-4c99-83c3-1241d42cc107.png">

**Comment by daisukes** [comment]
I see. How about `pod update` to check newer dependencies? 
Your `Podfile.lock` file seems to refers OpenCV-Dynamic 4.0.1 instead of 4.1.2
```
% pod update
```

**Comment by karthickkck315** [comment]
I am fixed that pod issue. But now am facing some issue in carthage. Can you please suggest me any solution. Please find the issue.
<img width="569" alt="Screenshot 2021-07-28 at 9 59 43 PM" src="https://user-images.githubusercontent.com/4092436/127360700-e1a3bbcf-ecc3-4ca2-b85d-8dcbe8891420.png">

**Comment by daisukes** [comment]
Have you tried workaround for XCode 12?
https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

**Comment by karthickkck315** [comment]
Am using XCode 12.4. But am getting same issue. Please find the screen shot.
<img width="570" alt="Screenshot 2021-07-29 at 11 42 54 AM" src="https://user-images.githubusercontent.com/4092436/127440798-1d4bef2d-e2c9-49ab-812b-0e4324e543f0.png">

**Comment by daisukes** [comment]
Please try to make a shell file suggested in the work around.

**Comment by karthickkck315** [comment]
Can you please give me any suggestions for "Incompatible  Swift version" issue. How can i fix this issue ?. Am searching many sites but i can't fix this one.

**Comment by daisukes** [comment]
Swift version is not the issue. It is related to arm64 binary for Apple M1 chip.
![EF9BD817-132F-4E43-AEC9-C3D7746A9863](https://user-images.githubusercontent.com/43101027/127506279-e205e21f-14a3-4689-8beb-0b52ea94079e.jpeg)


Please read this instruction carefully. This is known issue of XCode12 and Carthage.
https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

**Comment by daisukes** [comment]
@karthickkck315 

I will close this issue.
If you have more questions, please let me know.
