### ISSUE TITLE
cocoapods and carthage build problem

### ISSUE THREAD

**Issue by hiroshi-shin** [hulop/NavCogIOSv3#52]
**Environment**

Device: MacBook Pro M1
Carthage and Cocoapods installed from brew.

**Summary**
There are two main problems
1. podspec: No such file or directory
2. AMSupportURLSession and AMSupportURLConnectionDelegate implemented with multiple libraries

**Carthage build command**:
`carthage build --platform ios --use-xcframeworks --no-use-binaries`

**Results**: 
*** Building scheme "Mantle Mac" in Mantle.xcworkspace

> Build Failed
> 	Task failed with exit code 65:
> 	/usr/bin/xcrun xcodebuild -workspace /Users/shih107/XcodeProjects/NavCogIOSv3/Carthage/Checkouts/Mantle/Mantle.xcworkspace -scheme Mantle\ Mac -configuration Release -derivedDataPath /Users/shih107/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5.1_12E507/Mantle/2.0.7 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/lj/42hbp0w96_179rcbllrkfnfm0000gn/T/Mantle SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/shih107/XcodeProjects/NavCogIOSv3/Carthage/Checkouts/Mantle)

The log file:

> /usr/bin/xcrun xcodebuild -project /Users/xxx/XcodeProjects/NavCogIOSv3/Carthage/Checkouts/HLPWebView/HLPWebView.xcodeproj -scheme HLPWebView -configuration Release -derivedDataPath /Users/xxx/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5.1_12E507/HLPWebView/v1.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/lj/42hbp0w96_179rcbllrkfnfm0000gn/T/HLPWebView SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xxx/XcodeProjects/NavCogIOSv3/Carthage/Checkouts/HLPWebView)objc[28343]: Class **AMSupportURLConnectionDelegate** is implemented in both /usr/lib/libauthinstall.dylib (0x1f536bad8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x113ddc2b8). One of the two will be used. Which one is undefined.
> objc[28343]: Class **AMSupportURLSession** is implemented in both /usr/lib/libauthinstall.dylib (0x1f536bb28) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x113ddc308). One of the two will be used. Which one is undefined.

That's for Carthage. There are different situations for **Cocoapods**.

command: `pod install`

1. With the original Podfile in `master` branch:

> Errno::ENOENT - No such file or directory @ rb_sysopen - https://raw.githubusercontent.com/hulop/blelocpp/v1.3.6/platform/ios/podspecs/OpenCV-Dynamic.podspec

2. After removing the podspec attribute for OpenCV-Dynamic:
(It takes nearly half an hour to compile.)
The same error as in the Carthage log file.

3. Installing OpenCV-Dynamic in a brand new project:
```
CMake Error at cmake/OpenCVCompilerOptions.cmake:21 (else):
  Flow control statements are not properly nested.
Call Stack (most recent call first):
  CMakeLists.txt:499 (include)
```

4. After replacing OpenCV-Dynamic with LegoCV:
The same _AMSupportURLSession_ and _AMSupportURLConnectionDelegate_ problem

I searched for the answers that related to AMSupportURLSession and AMSupportURLConnectionDelegate implementation, but all those are about flutter.
It did not make sense to clean or rebuild this project.

I'm still new to the iOS native frameworks. Please let me know if I misunderstood some basic concepts.

**Comment by daisukes** [comment]
Hi @hiroshi-shin,

Could you please check #52 for carthage build error?

As for the pod install issue, can you access the podspec URL with your browser or `wget` command?

**Comment by daisukes** [comment]
I tried `homebrew` version of cocoapods and got the same error.
Could you please install `cocoapods` with the following command?
```
$ sudo gem install cocoapods
```

**Comment by hiroshi-shin** [comment]
> Hi @hiroshi-shin,
> 
> Could you please check #53 for carthage build error and build with the following command?
> `carthage build --platform ios`
> 
> As for the pod install issue, can you access the podspec URL with your browser or `wget` command?

Thank you. `carthage build --platform ios` without other flags worked.

> I tried homebrew version of cocoapods and got the same error.
> Could you please install cocoapods with the following command?

I got some problem with ruby for gem cocoapods, but I will try to fix it up this time.

**Comment by hiroshi-shin** [comment]
Cocoapods is finally built successfully.
Thank you for the quick reply.
