### ISSUE TITLE
Swift BlindViewController and ViewController initialization problem

### ISSUE THREAD

**Issue by hiroshi-shin** [hulop/NavCogIOSv3#54]
**Problem**:

When initializing those ViewControllers, some of the `IBOutlet` properties are not initialized, and gives error message when being called

`let vc = Util.routeMode == .blind ? BlindViewController() : ViewController()`

BlindViewController#[cover](https://github.com/miraikan-research/NavCogIOSv3/blob/miraikan-views-added/NavCog3/BlindViewController.m#:~:text=%5Belements%20addObject%3A_cover%5D%3B)

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

ViewController#[settingButton](https://github.com/miraikan-research/NavCogIOSv3/blob/miraikan-views-added/NavCog3/ViewController.m#:~:text=self.navigationItem.rightBarButtonItems%20%3D%20%40%5B%5D%3B-,self.navigationItem.leftBarButtonItems%20%3D%20%40%5Bself.settingButton%5D%3B,-break%3B)

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'

I understand that those ViewController are created from StoryBoard, and it would be easier to `performSegueWithIdentifier`. However, it would be better to understand what mistakes I made in this case.

**Expected Solutions**:

1. ~~Create the new ViewControllers by myself.~~
2. Instantiate the ViewControllers in a different way.
3. Create a ~~ViewController~~ UINavigationController on StoryBoard and add the segues 

Please let me know if there is any suggestions.

Thank you.

Update: 
- StoryBoard display problem fixed.
- Temporarily fixed the problem with Solution 3

**Comment by daisukes** [comment]
If UIView is created by interface builder, initWithCoder method is called and it initializes IBoutlets. However if you create just an instance, you need to set them in the init method.

You can use storyboard methed to create a view.

https://developer.apple.com/documentation/uikit/uistoryboard/1616214-instantiateviewcontroller

**Comment by hiroshi-shin** [comment]
Thank you very much.
After accessing the storyboard, I was able to performSegue and instantiate ViewControllers.
