### ISSUE TITLE
HLPDialog not starting 

### ISSUE THREAD

**Issue by hiroshi-shin** [hulop/NavCogIOSv3#59]
**Summary**

I'm trying to open the `HLPDialog` from my customized Tab. It was opened with some problem on tts, while the view state was `inactive`.

Here is the [details](https://github.com/miraikan-research/NavCog-Miraikan/issues/2). Please let me know if I missed any settings. Thank you.

**Comment by daisukes** [comment]
Thank you for letting me know about your issue.
You can just mention me in the issue of your repository to notify me!
