### ISSUE TITLE
Voice Guide Related Problem

### ISSUE THREAD

**Issue by hiroshi-shin** [hulop/NavCogIOSv3#61]
**The original issue**:

https://github.com/miraikan-research/NavCog-Miraikan/issues/18

**Additional description**:

I have recognized the low volume problem at the beginning. It was not happening on NavCog3 that time, and I thought there was something wrong with my code.

However, after the last system update, both my customized app and NavCog3 are in low volume, while the voice recognition is not started.

Please let me know if there is any updates required. Thank you.

**Comment by daisukes** [comment]
Hi @hiroshi-shin 

Thank you for submitting the issue.
I want to move this issue to HLPDialog's issue

https://github.com/hulop/HLPDialog/issues/1
