### ISSUE TITLE
Using wow-hokoukukan.bluemix.net

### ISSUE THREAD

**Issue by jpvguerreiro** [hulop/NavCogIOSv3#7]
Dragan and I tried to use the wow-hokoukukan server to test, but no destinations were found. We changed the server in the app, and also tried to change it in SettingViewController.m (HOST_Port setting):

[detailSettingHelper addSettingWithType:HOST_PORT Label:@"Server" Name:@"hokoukukan_server" DefaultValue:@[@"**wow-**hokoukukan.mybluemix.net"] Accept:nil];

**Comment by dsato80** [comment]
Hi @jpvguerreiro 

You need to scroll the map to a place where close to destinations (500 meters)
With wow-hokoukukan server, you should go to Las Vegas https://goo.gl/maps/6mJke4nf6ut
